import 'package:flutter_test/flutter_test.dart';
import 'package:fmhy_app/models/models.dart';
import 'package:fmhy_app/services/fm_parser.dart';

void main() {
  final parser = FMParser();

  group('FMParser', () {
    test('parses categories, sections, notes and entries', () {
      const md = '''
# ► Adblocking

* **Note** - Use an adblocker.

***

* ⭐ **[uBlock Origin](https://github.com/gorhill/uBlock)**, [AdGuard](https://adguard.com) - Adblockers / [Note](https://fmhy.net/n) - Extra
* ↪️ **[Twitch Adblockers](https://reddit.com/t)**

***

## ▷ DNS Adblocking

* **Note** - Careful with conflicts.

***

* 🌐 **[FilterLists](https://filterlists.com/)** - Filter directory
''';

      final cats = parser.parse(md);
      expect(cats, hasLength(1));

      final cat = cats.first;
      expect(cat.title, 'Adblocking');
      expect(cat.isLink, isFalse);
      expect(cat.note, contains('Use an adblocker'));
      expect(cat.entries, hasLength(2));

      // Featured badge, multiple links, cleaned description.
      // Inline link text in the description is preserved for context.
      final ubo = cat.entries.first;
      expect(ubo.name, 'uBlock Origin');
      expect(ubo.url, 'https://github.com/gorhill/uBlock');
      expect(ubo.badge, FMBadge.star);
      expect(ubo.relatedLinks.map((l) => l.name), ['AdGuard', 'Note']);
      expect(ubo.description, 'Adblockers / Note - Extra');

      // Arrow badge entry.
      expect(cat.entries[1].badge, FMBadge.arrow);

      // Section parsing.
      expect(cat.sections, hasLength(1));
      expect(cat.sections.first.title, 'DNS Adblocking');
      expect(cat.sections.first.note, contains('conflicts'));
      expect(cat.sections.first.entries.first.badge, FMBadge.globe);
      expect(cat.totalEntries, 3);
    });

    test('treats linked category headings as link entries', () {
      const md = '''
# ► [Index](https://fmhy.net)

# ► Audio

* [Site](https://example.com)
''';
      final cats = parser.parse(md);
      expect(cats, hasLength(2));
      expect(cats.first.title, 'Index');
      expect(cats.first.url, 'https://fmhy.net');
      expect(cats.first.isLink, isTrue);
    });

    test('ignores comments and nav chrome', () {
      const md = '''
<!-- autogenerated -->
***
**[◄◄ Back to Wiki Index](https://reddit.com/wiki/index)**
***

# ► Tools

* [One](https://a.com)
''';
      final cats = parser.parse(md);
      expect(cats, hasLength(1));
      expect(cats.first.title, 'Tools');
      expect(cats.first.entries, hasLength(1));
    });

    test('skips lines without a usable link', () {
      const md = '''
# ► Tools

* not a link at all
* [Real](https://real.com)
''';
      final cats = parser.parse(md);
      expect(cats.first.entries, hasLength(1));
      expect(cats.first.entries.first.name, 'Real');
    });

    test('entry with no description yields null', () {
      const md = '''
# ► Tools

* [Plain](https://plain.com)
''';
      final cats = parser.parse(md);
      expect(cats.first.entries.first.description, isNull);
    });

    test('real-world line keeps the trailing prose description', () {
      const md = '''
# ► Adblocking

* ⭐ **[SponsorBlock](https://sponsor.ajay.app/)** - Skip Sponsored YouTube Ads / [X](https://x.com/SponsorBlock) / [Discord](https://discord.gg/SponsorBlock)
''';
      final cats = parser.parse(md);
      final entry = cats.first.entries.single;
      expect(entry.name, 'SponsorBlock');
      expect(entry.relatedLinks.map((l) => l.name), ['X', 'Discord']);
      expect(entry.description, 'Skip Sponsored YouTube Ads / X / Discord');
    });
  });

  group('FMCategory.filter', () {
    final category = FMCategory(
      title: 'Audio',
      entries: const [
        FMEntry(name: 'Spotify Tweak', url: 'https://a.com', description: 'mod'),
        FMEntry(name: 'Bandcamp', url: 'https://b.com'),
      ],
      sections: const [
        FMSection(
          title: 'Music Apps',
          entries: [FMEntry(name: 'Spotify', url: 'https://c.com')],
        ),
      ],
    );

    test('matches on name', () {
      final r = category.filter('spotify');
      expect(r.entries, hasLength(1));
      expect(r.sections, hasLength(1));
      expect(r.sections.first.entries.single.name, 'Spotify');
    });

    test('matches on description and url', () {
      expect(category.filter('mod').entries.single.name, 'Spotify Tweak');
      expect(category.filter('b.com').entries.single.name, 'Bandcamp');
    });

    test('throws when nothing matches', () {
      expect(() => category.filter('zzz'), throwsStateError);
    });
  });
}
